---
title: "NSFL/ISFL Scorigami"
author: "Mojojojo"
date: "September 18, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up
```{r packages, warning = FALSE, message=FALSE}
library(ggplot2)
library(viridis) #color-blind friendly palette for figures
library(dplyr)
library(reshape2) #melt function
library(tidyverse)
library(grid)
library(gridExtra)
```


## Load data
```{r data, warning = FALSE}
#Read-in NSFL/ISFL game data
data_full <- read.csv("./ISFL_scorigami.csv", stringsAsFactors=FALSE, na.strings=c("","NA"))
colnames(data_full)

#Read-in spreadsheet of impossible scores
data_impossible <- read.csv("./ImpossibleScores.csv", stringsAsFactors=FALSE, na.strings=c("","NA"))

#Merge and create impossible flag
data_full <- rbind(data_full, data_impossible)
data_full <- data_full %>% mutate(Imp = ifelse(WinType=="IMPOSSIBLE", "Yes", "No"))
data_full$score_pair <- paste(data_full$FinalScore_won, data_full$FinalScore_lost, sep = "_")

games_season <- group_by(data_full, Season)  %>% tally()

```

# Visualizing Scorigami Grids
```{r vizgrids, warning=FALSE}
#Filter dataframe down to unique score pairs
unique.scores <- rownames(unique(data_full[,c('FinalScore_won', 'FinalScore_lost')]))
data_unique <- data_full[rownames(data_full[,])%in%unique.scores, ]

#Number and proportion of games resulting in scorigami per season
scorigami_num <- group_by(data_unique, Season)  %>% tally()
scorigami_num$p <- scorigami_num$n / games_season$n
scorigami_num$n.tot <- games_season$n
scorigami_num <- scorigami_num[1:24,]

p1 <- ggplot(scorigami_num, aes(x=Season)) +
        geom_col(aes(y=n)) +
        #geom_line(aes(x=Season, y=n.tot)) + 
        geom_text(aes(y=n, label=n), vjust=-0.5, size=4) + 
        ggtitle("Number of NSFL/ISFL games that are scorigami per season") +
        xlab("Season") + ylab("Number of scorigami") +
        scale_x_continuous(breaks=0:24, labels=0:24, expand=c(0,0)) +
        scale_y_continuous(limits=c(0,55)) + #sec.axis = sec_axis(~.*2, name="Total games played")
        theme_bw()

p2 <- ggplot(scorigami_num) +
        geom_col(aes(x=Season, y=p)) +
        geom_text(aes(x=Season, y=p, label=round(p, 2)), vjust=-0.5, size=4) +
        ggtitle("Proportion of NSFL/ISFL games that end in scorigami per season") +
        xlab("Season") + ylab("Proportion of games that \n end in scorigami") +
        scale_y_continuous(limits=c(0,1)) +
        scale_x_continuous(breaks=0:24, labels=0:24, expand=c(0,0)) +
        theme_bw()

p <- arrangeGrob(p1, p2)
p
#ggsave(filename="ISFLscorigami_trends.jpg", plot=p, width=10, height=5, units="in", dpi=800)


#Simple scorigami grid
ggplot(data=data_unique, aes(x=FinalScore_won, y=FinalScore_lost, fill=Imp)) +
  geom_tile() +
  ggtitle("NSFL/ISFL scorigami (S24 update)") +
  ylab("Losing team score") + xlab("Winning team score") +
  #add grid lines and labels for every integer
  scale_y_reverse(breaks=0:42, labels=0:42, expand=c(0,0), position="right") + 
  scale_x_continuous(breaks=0:80, labels=0:80, expand=c(0,0), position="top") +
  scale_fill_manual(values=c("darkgreen", "darkgrey")) +
  theme_bw() +
  theme(panel.grid.minor=element_blank(), legend.position="none")
#ggsave(filename="ISFLscorigami_basic.jpg", plot=last_plot(), width=13, height=7, units="in", dpi=800)


#Color seasons since last scorigami post (season 18 on)
data_unique <- data_unique %>% mutate(Season2 = ifelse(Season < 18, '1-17', Season))

palette <- viridis(8)
ggplot(data=data_unique, aes(x=FinalScore_won, y=FinalScore_lost, fill=Season2)) +
  geom_tile() +
  ggtitle("NSFL/ISFL scorigami (S24 update)") +
  ylab("Losing team score") + xlab("Winning team score") +
  labs(fill="Season") +
  #add grid lines and labels for every integer
  scale_y_reverse(breaks=0:42, labels=0:42, expand=c(0,0), position="right") + 
  scale_x_continuous(breaks=0:80, labels=0:80, expand=c(0,0), position="top") +
  scale_fill_manual(values=palette, na.value="darkgrey") +
  theme_bw() +
  theme(panel.grid.minor=element_blank())
#ggsave(filename="ISFLscorigami_season.jpg", plot=last_plot(), width=14, height=7, units="in", dpi=800)


#Add color saturation for number of times score has happened
data_full$score_pair <- as.factor(data_full$score_pair)
score_count <- group_by(data_full, score_pair) %>% summarise(n=length(score_pair))
score_count <- merge(score_count, subset(data_unique, select=c("score_pair","FinalScore_won", "FinalScore_lost","Imp")), by="score_pair")
score_count <- score_count %>% mutate(n = ifelse(Imp=="Yes", NA, n))
                     
ggplot(data=score_count, aes(x=FinalScore_won, y=FinalScore_lost, fill=n)) +
  geom_tile() +
  ggtitle("NSFL/ISFL scorigami (S24 update)") +
  ylab("Losing team score") + xlab("Winning team score") +
  labs(fill="Count") +
  #add grid lines and labels for every integer
  scale_y_reverse(breaks=0:42, labels=0:42, expand=c(0,0), position="right") + 
  scale_x_continuous(breaks=0:80, labels=0:80, expand=c(0,0), position="top") +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen") +
  #scale_fill_manual(values=c("darkgreen", "darkgrey")) +
  theme_bw() +
  theme(panel.grid.minor=element_blank())
#ggsave(filename="ISFLscorigami_count.jpg", plot=last_plot(), width=14, height=7, units="in", dpi=800)

```

# Notable Scorigami
```{r notables, warning=FALSE}
#Total score
data_unique <- data_unique %>% mutate(TotalScore = FinalScore_won + FinalScore_lost)

#Scorigami occurring in the playoffs:
data_playoffs <- filter(data_unique, Week=="P") #P = playoff game
data_ultimus <- filter(data_unique, Week=="U") #U = ultimus match
data_ultimus[,1:7] #display recent Ultimus scorigami

#Top scorigami team since S22 expansion
data_S22on <- filter(data_unique, Season > 21)
scorigami_teamwon <- group_by(data_S22on, Team_won)  %>% tally()
scorigami_teamlost <- group_by(data_S22on, Team_lost)  %>% tally()

scorigami_team <- merge(scorigami_teamwon, scorigami_teamlost, by.x="Team_won", by.y="Team_lost")
scorigami_team <- scorigami_team %>% mutate(Total = n.x + n.y)
colnames(scorigami_team) <- c("Team", "ScorigamisWon", "ScorigamisLost", "ScorigamisTotal")
scorigami_team <- scorigami_team %>% mutate(Won_p = ScorigamisWon/ScorigamisTotal, Lost_p = ScorigamisLost/ScorigamisTotal)

scorigami_team

```

